[package]
name = "infrablockspace-node-primitives"
description = "Primitives types for the Node-side"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
bounded-vec = "0.7"
futures = "0.3.21"
infrablockspace-primitives = { path = "../../primitives" }
parity-scale-codec = { version = "3.3.0", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
sp-application-crypto = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
sp-consensus-vrf = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
sp-consensus-babe = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
sp-keystore = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
sp-maybe-compressed-blob = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
sp-runtime = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
frame-support = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master", default-features = false }
infrablockspace-parachain = { path = "../../parachain", default-features = false }
schnorrkel = "0.9.1"
thiserror = "1.0.31"
serde = { version = "1.0.137", features = ["derive"] }

[target.'cfg(not(target_os = "unknown"))'.dependencies]
zstd = { version = "0.12.4", default-features = false }

[dev-dependencies]
erasure-coding = { path = "../../erasure-coding" }
